### PR TITLE
Export all content in one HTML Document 

### PR DESCRIPTION
**Pull request by astridx**
One point on the list of future features are other formats such as mobi, epub or PDF. For this, in my opinion, a single HTML page is a good basis. Maybe you like my beginning.

### CODE REVIEW

**Comment by trendschau** [comment]
Hi Astrid, great, thank you for that contribution! I will check it asap next week when I am back.

**Comment by trendschau** [comment]
Hi Astrid, I looked into it and it looks great, thank you! The use case is probably not ready for production yet, so I added your changes to another branch. As you said I want to use it as a starting point and maybe create individual plugins for that. So I will use the separate branch to work on it and when it is ready I will merge it to master :)

**Comment by astridx** [comment]
I'm glad you like my start. Do I understand you correctly: You want to convert all the code for the export as a plugin?

**Comment by trendschau** [comment]
Hi Astrid, I want to investigate the best way, maybe only parts of it as a plugin and models in core, but I am not sure yet. The initial idea of Typemill was to provide the whole website in different formats (html, epub and more) either in frontend for all users or only for registered users, so authors can try to monetize their work (e.g. with export formats and pro content for registered users). But it is a long way to go and I want to take some time to think about it. Another idea was to optionally statify the whole website, so the html-export might also be a starting point for that. But I did not had the time to investigate details yet...

**Pull request closed without merging**
